name: Admin Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/admin/**"
      - "firebase.json"
      - ".firebaserc"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/admin-deploy.yaml"

jobs:
  build-and-deploy-admin:
    name: Build and Deploy Admin
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Inject Firebase Configuration
        run: printf "%s" "$FIREBASE_CONFIG" > frontend/admin/.env
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_RESTORED_CHURCH_PLATFORM_APP_CONFIG }}

      - name: Build and Deploy Admin Portal
        run: pnpm deploy:admin
