---
name: Continuous Integration (CI)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format:check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:coverage

      - name: Report Coverage (Deposit Counter)
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Coverage Report (Deposit Counter)
          working-directory: ./frontend/deposit-counter
          file-coverage-mode: all
