---
name: Integration Tests

on:
  push:
    branches: [main]

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        with:
          cache: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Integration Tests
        run: pnpm --filter pushpay-sync test:integration
